### ISSUE TITLE
Can't configure IPv4 and IPv6 address using cumulus_interface

### ISSUE THREAD

**Issue by zioproto** [CumulusNetworks/cumulus-cl-interfaces-puppet#21]
Using the following code:
```
cumulus_interface { 'swp1':
  ipv4 => ['10.1.1.45/32'],
  ipv6 => ['2001:620:5ca1:101::45/64'],
  notify => Service['networking'],

}
```
Will produce on the switch after running the puppet agent the following file:
```
proto@sw-e:/$ cat /etc/network/interfaces.d/swp1
auto swp1
iface swp1
	address 10.1.1.45/32 2001:620:5ca1:101::45/64
```
That is not correct, infact you will have no addresses in your interface
```
proto@sw-e:/$ sudo ifup swp1
warning: failed to execute cmd 'ip -force -batch - [addr add 10.1.1.45/32 2001:620:5ca1:101::45/64 dev swp1
]'(Error: either "local" is duplicate, or "2001:620:5ca1:101::45/64" is a garbage.)
```
The expected syntax would be
```
proto@sw-e:/$ cat /etc/network/interfaces.d/swp1
auto swp1
iface swp1
      address 10.1.1.45/32 
      address 2001:620:5ca1:101::45/64
```

**Comment by zioproto** [comment]
As far as I understand the problem comes from here:

https://github.com/CumulusNetworks/cumulus-cl-interfaces-puppet/blob/master/lib/cumulus/ifupdown2.rb#L75

I tried to rework `addresslist` to be an array. However iterating the array and calling multiple times
```
@confighash['config']['address'] = addresslistelement
```
will not work because this `confighash` thing is not meant to have multiple `address` statements.

However this should be possible looking at the example documentation:
http://docs.cumulusnetworks.com/display/DOCS/Configuring+and+Managing+Network+Interfaces

You can specify both IPv4 and IPv6 addresses in the same iface stanza:
```
auto swp1
iface swp1
    address 192.0.2.1/30
    address 192.0.2.2/30
    address 2001:DB8::1/126
```

**Comment by LeslieCarr** [comment]
Thanks for the super detailed bug report :) We'll get on this

**Comment by zioproto** [comment]
Should I keep an eye on this new branch ce-1130-ipv6-addresses ?
I see the new branch in the repo but no new commits. Thanks.

**Comment by LeslieCarr** [comment]
Hi - I started that branch but haven't yet successfully fixed the problem.  @Vanders will probably also be helping!

**Comment by zioproto** [comment]
Hello there,
there is any estimate on when this could be fixed ?
@LeslieCarr you were able to reproduce the bug? Is the bug confirmed ?

We have some stuff to setup in our Datacenter. I need to understand if I have to go on and configure the all thing by hand, or if I can use these puppet tools.

Thanks !

**Comment by LeslieCarr** [comment]
Hey -
yes I confirmed it is a problem but haven't yet been able to fix it (figure out how to fix it).  If you are in a big time crunch you could also use puppet templates for the interfaces --it's not as nice but it's way better than configuring by hand

**Comment by zioproto** [comment]
I will rework my module with templates to be indipendent from cumulus_interfaces library then.

I also tried to think of a patch to fix this problem, but needs a lot of refactoring. You need to rethink the 'address' keyword as a list and not as a dictionary.

I am not even sure if the bug is in this code or in ifquery.

**Comment by Vanders** [comment]
I think the bug may be a bit of both the module & ifquery. The module builds up the hash (as you've noted) and passes that to ifquery. The obvious problem is that we can't have a hash with more than one key of the same name, but we also can't pass a list of both IPv4 & IPv6 addresses to ifquery and have it do the right thing.

I'm going to dig into ifquery and see if there's a way to make it work without having to do some epic refactoring on the module but it might take some time as this is a bigger issue than it appears on the surface.

**Comment by Vanders** [comment]
Okay, I think I've got it. @zioproto could you try the version on the ce-1130-ipv6-addresses and let us know if that works for you?

**Comment by zioproto** [comment]
@Vanders I just tested and it works for me.

It would be nice to have a new release on puppet forge because a lot of bugs have been fixed.
We had to fork from:
https://forge.puppetlabs.com/cumuluslinux/cumulus_interfaces
So I tested against my own tree.

Is it time for 1.0.3.3 ?

**Comment by Vanders** [comment]
Cool! This was the outstanding issue before we did a release of all of the modules, so expect a release sometime within the next week.
